/*
 * TeamSpeak 3 Client Plugin SDK
 * Copyright (c) TeamSpeak Systems GmbH
 * Obtained via ACRE2 (https://github.com/IDI-Systems/acre2) — GPLv3
 */
#ifndef PUBLIC_RARE_DEFINITIONS_H
#define PUBLIC_RARE_DEFINITIONS_H

#include "public_definitions.h"

#define TS3_MAX_SIZE_CLIENT_NICKNAME_NONSDK 30
#define TS3_MIN_SIZE_CLIENT_NICKNAME_NONSDK 3
#define TS3_MAX_SIZE_AWAY_MESSAGE 80
#define TS3_MAX_SIZE_GROUP_NAME 30
#define TS3_MAX_SIZE_TALK_REQUEST_MESSAGE 50
#define TS3_MAX_SIZE_COMPLAIN_MESSAGE 200
#define TS3_MAX_SIZE_CLIENT_DESCRIPTION 200
#define TS3_MAX_SIZE_HOST_MESSAGE 200
#define TS3_MAX_SIZE_HOSTBUTTON_TOOLTIP 50
#define TS3_MAX_SIZE_POKE_MESSAGE 100
#define TS3_MAX_SIZE_OFFLINE_MESSAGE 4096
#define TS3_MAX_SIZE_OFFLINE_MESSAGE_SUBJECT 200

#define TS3_MAX_SIZE_PLUGIN_COMMAND 1024*8
#define TS3_MAX_SIZE_VIRTUALSERVER_HOSTBANNER_GFX_URL 2000

enum GroupShowNameTreeMode {
    GroupShowNameTreeMode_NONE= 0,
    GroupShowNameTreeMode_BEFORE,
    GroupShowNameTreeMode_BEHIND
};

enum PluginTargetMode {
    PluginCommandTarget_CURRENT_CHANNEL=0,
    PluginCommandTarget_SERVER,
    PluginCommandTarget_CLIENT,
    PluginCommandTarget_CURRENT_CHANNEL_SUBSCRIBED_CLIENTS,
    PluginCommandTarget_MAX
};

enum {
    SERVER_BINDING_VIRTUALSERVER=0,
    SERVER_BINDING_SERVERQUERY  =1,
    SERVER_BINDING_FILETRANSFER =2,
};

enum HostMessageMode {
    HostMessageMode_NONE=0,
    HostMessageMode_LOG,
    HostMessageMode_MODAL,
    HostMessageMode_MODALQUIT
};

enum HostBannerMode {
    HostBannerMode_NO_ADJUST=0,
    HostBannerMode_ADJUST_IGNORE_ASPECT,
    HostBannerMode_ADJUST_KEEP_ASPECT,
};

enum ClientType {
    ClientType_NORMAL = 0,
    ClientType_SERVERQUERY,
};

enum AwayStatus {
    AWAY_NONE = 0,
    AWAY_ZZZ,
};

enum CommandLinePropertiesRare {
#ifdef SERVER
    COMMANDLINE_CREATE_DEFAULT_VIRTUALSERVER= 0,
    COMMANDLINE_MACHINE_ID,
    COMMANDLINE_DEFAULT_VOICE_PORT,
    COMMANDLINE_VOICE_IP,
    COMMANDLINE_THREADS_VOICE_UDP,
    COMMANDLINE_LICENSEPATH,
#ifndef SDK
    COMMANDLINE_FILETRANSFER_PORT,
    COMMANDLINE_FILETRANSFER_IP,
    COMMANDLINE_QUERY_PORT,
    COMMANDLINE_QUERY_IP,
    COMMANDLINE_QUERY_IP_WHITELIST,
    COMMANDLINE_QUERY_IP_BLACKLIST,
    COMMANDLINE_CLEAR_DATABASE,
    COMMANDLINE_SERVERADMIN_PASSWORD,
    COMMANDLINE_DBPLUGIN,
    COMMANDLINE_DBPLUGINPARAMETER,
    COMMANDLINE_DBSQLPATH,
    COMMANDLINE_DBSQLCREATEPATH,
    COMMANDLINE_DBCONNECTIONS,
    COMMANDLINE_LOGPATH,
    COMMANDLINE_CREATEINIFILE,
    COMMANDLINE_INIFILE,
    COMMANDLINE_LOGQUERYCOMMANDS,
    COMMANDLINE_DBCLIENTKEEPDAYS,
    COMMANDLINE_NO_PERMISSION_UPDATE,
    COMMANDLINE_OPEN_WIN_CONSOLE,
    COMMANDLINE_NO_PASSWORD_DIALOG,
    COMMANDLINE_LOGAPPEND,
    COMMANDLINE_QUERY_SKIPBRUTEFORCECHECK,
    COMMANDLINE_QUERY_BUFFER_MB,
    COMMANDLINE_HTTP_PROXY,
    COMMANDLINE_LICENSE_ACCEPTED,
    COMMANDLINE_SERVERQUERYDOCS_PATH,
    COMMANDLINE_QUERY_SSH_IP,
    COMMANDLINE_QUERY_SSH_PORT,
    COMMANDLINE_QUERY_PROTOCOLS,
    COMMANDLINE_QUERY_SSH_RSA_HOST_KEY,
    COMMANDLINE_QUERY_TIMEOUT,
    COMMANDLINE_VERSION,
    COMMANDLINE_CRASHDUMPSPATH,
    COMMANDLINE_DAEMON,
    COMMANDLINE_PID_FILE,
    COMMANDLINE_HINTS_ENABLED,
#endif
#else
    COMMANDLINE_NOTHING=0,
#endif
    COMMANDLINE_ENDMARKER_RARE,
};

enum ServerInstancePropertiesRare {
    SERVERINSTANCE_DATABASE_VERSION= 0,
    SERVERINSTANCE_FILETRANSFER_PORT,
    SERVERINSTANCE_SERVER_ENTROPY,
    SERVERINSTANCE_MONTHLY_TIMESTAMP,
    SERVERINSTANCE_MAX_DOWNLOAD_TOTAL_BANDWIDTH,
    SERVERINSTANCE_MAX_UPLOAD_TOTAL_BANDWIDTH,
    SERVERINSTANCE_GUEST_SERVERQUERY_GROUP,
    SERVERINSTANCE_SERVERQUERY_FLOOD_COMMANDS,
    SERVERINSTANCE_SERVERQUERY_FLOOD_TIME,
    SERVERINSTANCE_SERVERQUERY_BAN_TIME,
    SERVERINSTANCE_TEMPLATE_SERVERADMIN_GROUP,
    SERVERINSTANCE_TEMPLATE_SERVERDEFAULT_GROUP,
    SERVERINSTANCE_TEMPLATE_CHANNELADMIN_GROUP,
    SERVERINSTANCE_TEMPLATE_CHANNELDEFAULT_GROUP,
    SERVERINSTANCE_PERMISSIONS_VERSION,
    SERVERINSTANCE_PENDING_CONNECTIONS_PER_IP,
    SERVERINSTANCE_SERVERQUERY_MAX_CONNECTIONS_PER_IP,
    SERVERINSTANCE_ENDMARKER_RARE,
};

enum VirtualServerPropertiesRare {
    VIRTUALSERVER_DUMMY_1 = VIRTUALSERVER_ENDMARKER,
    VIRTUALSERVER_DUMMY_2,
    VIRTUALSERVER_DUMMY_3,
    VIRTUALSERVER_DUMMY_4,
    VIRTUALSERVER_DUMMY_5,
    VIRTUALSERVER_DUMMY_6,
    VIRTUALSERVER_DUMMY_7,
    VIRTUALSERVER_DUMMY_8,
    VIRTUALSERVER_KEYPAIR,
    VIRTUALSERVER_HOSTMESSAGE,
    VIRTUALSERVER_HOSTMESSAGE_MODE,
    VIRTUALSERVER_FILEBASE,
    VIRTUALSERVER_DEFAULT_SERVER_GROUP,
    VIRTUALSERVER_DEFAULT_CHANNEL_GROUP,
    VIRTUALSERVER_FLAG_PASSWORD,
    VIRTUALSERVER_DEFAULT_CHANNEL_ADMIN_GROUP,
    VIRTUALSERVER_MAX_DOWNLOAD_TOTAL_BANDWIDTH,
    VIRTUALSERVER_MAX_UPLOAD_TOTAL_BANDWIDTH,
    VIRTUALSERVER_HOSTBANNER_URL,
    VIRTUALSERVER_HOSTBANNER_GFX_URL,
    VIRTUALSERVER_HOSTBANNER_GFX_INTERVAL,
    VIRTUALSERVER_COMPLAIN_AUTOBAN_COUNT,
    VIRTUALSERVER_COMPLAIN_AUTOBAN_TIME,
    VIRTUALSERVER_COMPLAIN_REMOVE_TIME,
    VIRTUALSERVER_MIN_CLIENTS_IN_CHANNEL_BEFORE_FORCED_SILENCE,
    VIRTUALSERVER_PRIORITY_SPEAKER_DIMM_MODIFICATOR,
    VIRTUALSERVER_ID,
    VIRTUALSERVER_ANTIFLOOD_POINTS_TICK_REDUCE,
    VIRTUALSERVER_ANTIFLOOD_POINTS_NEEDED_COMMAND_BLOCK,
    VIRTUALSERVER_ANTIFLOOD_POINTS_NEEDED_IP_BLOCK,
    VIRTUALSERVER_CLIENT_CONNECTIONS,
    VIRTUALSERVER_QUERY_CLIENT_CONNECTIONS,
    VIRTUALSERVER_HOSTBUTTON_TOOLTIP,
    VIRTUALSERVER_HOSTBUTTON_URL,
    VIRTUALSERVER_HOSTBUTTON_GFX_URL,
    VIRTUALSERVER_QUERYCLIENTS_ONLINE,
    VIRTUALSERVER_DOWNLOAD_QUOTA,
    VIRTUALSERVER_UPLOAD_QUOTA,
    VIRTUALSERVER_MONTH_BYTES_DOWNLOADED,
    VIRTUALSERVER_MONTH_BYTES_UPLOADED,
    VIRTUALSERVER_TOTAL_BYTES_DOWNLOADED,
    VIRTUALSERVER_TOTAL_BYTES_UPLOADED,
    VIRTUALSERVER_PORT,
    VIRTUALSERVER_AUTOSTART,
    VIRTUALSERVER_MACHINE_ID,
    VIRTUALSERVER_NEEDED_IDENTITY_SECURITY_LEVEL,
    VIRTUALSERVER_LOG_CLIENT,
    VIRTUALSERVER_LOG_QUERY,
    VIRTUALSERVER_LOG_CHANNEL,
    VIRTUALSERVER_LOG_PERMISSIONS,
    VIRTUALSERVER_LOG_SERVER,
    VIRTUALSERVER_LOG_FILETRANSFER,
    VIRTUALSERVER_MIN_CLIENT_VERSION,
    VIRTUALSERVER_NAME_PHONETIC,
    VIRTUALSERVER_ICON_ID,
    VIRTUALSERVER_RESERVED_SLOTS,
    VIRTUALSERVER_TOTAL_PACKETLOSS_SPEECH,
    VIRTUALSERVER_TOTAL_PACKETLOSS_KEEPALIVE,
    VIRTUALSERVER_TOTAL_PACKETLOSS_CONTROL,
    VIRTUALSERVER_TOTAL_PACKETLOSS_TOTAL,
    VIRTUALSERVER_TOTAL_PING,
    VIRTUALSERVER_IP,
    VIRTUALSERVER_WEBLIST_ENABLED,
    VIRTUALSERVER_AUTOGENERATED_PRIVILEGEKEY,
    VIRTUALSERVER_ASK_FOR_PRIVILEGEKEY,
    VIRTUALSERVER_HOSTBANNER_MODE,
    VIRTUALSERVER_CHANNEL_TEMP_DELETE_DELAY_DEFAULT,
    VIRTUALSERVER_MIN_ANDROID_VERSION,
    VIRTUALSERVER_MIN_IOS_VERSION,
    VIRTUALSERVER_MIN_WINPHONE_VERSION,
    VIRTUALSERVER_NICKNAME,
    VIRTUALSERVER_ACCOUNTING_TOKEN,
    VIRTUALSERVER_PROTOCOL_VERIFY_KEYPAIR,
    VIRTUALSERVER_ANTIFLOOD_POINTS_NEEDED_PLUGIN_BLOCK,
    VIRTUALSERVER_ENDMARKER_RARE
};

enum ChannelPropertiesRare {
    CHANNEL_DUMMY_3=CHANNEL_ENDMARKER,
    CHANNEL_DUMMY_4,
    CHANNEL_DUMMY_5,
    CHANNEL_DUMMY_6,
    CHANNEL_DUMMY_7,
    CHANNEL_FLAG_MAXCLIENTS_UNLIMITED,
    CHANNEL_FLAG_MAXFAMILYCLIENTS_UNLIMITED,
    CHANNEL_FLAG_MAXFAMILYCLIENTS_INHERITED,
    CHANNEL_FLAG_ARE_SUBSCRIBED,
    CHANNEL_FILEPATH,
    CHANNEL_NEEDED_TALK_POWER,
    CHANNEL_FORCED_SILENCE,
    CHANNEL_NAME_PHONETIC,
    CHANNEL_ICON_ID,
    CHANNEL_BANNER_GFX_URL,
    CHANNEL_BANNER_MODE,
    CHANNEL_PERMISSION_HINTS,
    CHANNEL_ENDMARKER_RARE,
    CHANNEL_DELETE_DELAY_DEADLINE = 127
};

enum ClientPropertiesRare {
    CLIENT_DUMMY_4 = CLIENT_ENDMARKER,
    CLIENT_DUMMY_5,
    CLIENT_DUMMY_6,
    CLIENT_DUMMY_7,
    CLIENT_DUMMY_8,
    CLIENT_DUMMY_9,
    CLIENT_KEY_OFFSET,
    CLIENT_LAST_VAR_REQUEST,
    CLIENT_LOGIN_NAME,
    CLIENT_LOGIN_PASSWORD,
    CLIENT_DATABASE_ID,
    CLIENT_CHANNEL_GROUP_ID,
    CLIENT_SERVERGROUPS,
    CLIENT_CREATED,
    CLIENT_LASTCONNECTED,
    CLIENT_TOTALCONNECTIONS,
    CLIENT_AWAY,
    CLIENT_AWAY_MESSAGE,
    CLIENT_TYPE,
    CLIENT_FLAG_AVATAR,
    CLIENT_TALK_POWER,
    CLIENT_TALK_REQUEST,
    CLIENT_TALK_REQUEST_MSG,
    CLIENT_DESCRIPTION,
    CLIENT_IS_TALKER,
    CLIENT_MONTH_BYTES_UPLOADED,
    CLIENT_MONTH_BYTES_DOWNLOADED,
    CLIENT_TOTAL_BYTES_UPLOADED,
    CLIENT_TOTAL_BYTES_DOWNLOADED,
    CLIENT_IS_PRIORITY_SPEAKER,
    CLIENT_UNREAD_MESSAGES,
    CLIENT_NICKNAME_PHONETIC,
    CLIENT_NEEDED_SERVERQUERY_VIEW_POWER,
    CLIENT_DEFAULT_TOKEN,
    CLIENT_ICON_ID,
    CLIENT_IS_CHANNEL_COMMANDER,
    CLIENT_COUNTRY,
    CLIENT_CHANNEL_GROUP_INHERITED_CHANNEL_ID,
    CLIENT_BADGES,
    CLIENT_MYTEAMSPEAK_ID,
    CLIENT_INTEGRATIONS,
    CLIENT_ACTIVE_INTEGRATIONS_INFO,
    CLIENT_MYTS_AVATAR,
    CLIENT_SIGNED_BADGES,
    CLIENT_PERMISSION_HINTS,
    CLIENT_ENDMARKER_RARE,
    CLIENT_HW_ID = 127
};

enum ConnectionPropertiesRare {
    CONNECTION_DUMMY_0= CONNECTION_ENDMARKER,
    CONNECTION_DUMMY_1,
    CONNECTION_DUMMY_2,
    CONNECTION_DUMMY_3,
    CONNECTION_DUMMY_4,
    CONNECTION_DUMMY_5,
    CONNECTION_DUMMY_6,
    CONNECTION_DUMMY_7,
    CONNECTION_DUMMY_8,
    CONNECTION_DUMMY_9,
    CONNECTION_FILETRANSFER_BANDWIDTH_SENT,
    CONNECTION_FILETRANSFER_BANDWIDTH_RECEIVED,
    CONNECTION_FILETRANSFER_BYTES_RECEIVED_TOTAL,
    CONNECTION_FILETRANSFER_BYTES_SENT_TOTAL,
    CONNECTION_ENDMARKER_RARE,
};

enum BBCodeTags {
    BBCodeTag_B           = 0x00000001,
    BBCodeTag_I           = 0x00000002,
    BBCodeTag_U           = 0x00000004,
    BBCodeTag_S           = 0x00000008,
    BBCodeTag_SUP         = 0x00000010,
    BBCodeTag_SUB         = 0x00000020,
    BBCodeTag_COLOR       = 0x00000040,
    BBCodeTag_SIZE        = 0x00000080,
    BBCodeTag_group_text  = 0x000000FF,
    BBCodeTag_LEFT        = 0x00001000,
    BBCodeTag_RIGHT       = 0x00002000,
    BBCodeTag_CENTER      = 0x00004000,
    BBCodeTag_group_align = 0x00007000,
    BBCodeTag_URL         = 0x00010000,
    BBCodeTag_IMAGE       = 0x00020000,
    BBCodeTag_HR          = 0x00040000,
    BBCodeTag_LIST        = 0x00100000,
    BBCodeTag_LISTITEM    = 0x00200000,
    BBCodeTag_group_list  = 0x00300000,
    BBCodeTag_TABLE       = 0x00400000,
    BBCodeTag_TR          = 0x00800000,
    BBCodeTag_TH          = 0x01000000,
    BBCodeTag_TD          = 0x02000000,
    BBCodeTag_group_table = 0x03C00000,
    BBCodeTag_def_simple     = BBCodeTag_B | BBCodeTag_I | BBCodeTag_U | BBCodeTag_S | BBCodeTag_SUP | BBCodeTag_SUB |BBCodeTag_COLOR | BBCodeTag_URL,
    BBCodeTag_def_simple_Img = BBCodeTag_def_simple | BBCodeTag_IMAGE,
    BBCodeTag_def_extended   = BBCodeTag_group_text | BBCodeTag_group_align | BBCodeTag_URL | BBCodeTag_IMAGE | BBCodeTag_HR | BBCodeTag_group_list | BBCodeTag_group_table,
};

enum LicenseIssue {
    Blacklisted = 0,
    Greylisted
};

enum MytsDataUnsetFlags {
    MytsDataUnsetFlag_None   = 0,
    MytsDataUnsetFlag_Badges = 1,
    MytsDataUnsetFlag_Avatar = 1 << 1,
    MytsDataUnsetFlag_All = MytsDataUnsetFlag_Badges | MytsDataUnsetFlag_Avatar
};

typedef int(*ExtraBBCodeValidator)(void* userparam, const char* tag, const char* paramValue, int paramValueSize, const char* childValue, int childValueSize);
typedef const char* (*ExtraBBCodeParamTransform)(void* userparam, const char* tag, const char* paramValue);

#endif //PUBLIC_RARE_DEFINITIONS_H
