/*
 * TeamSpeak 3 Client Plugin SDK
 * Copyright (c) TeamSpeak Systems GmbH
 * Obtained via ACRE2 (https://github.com/IDI-Systems/acre2) — GPLv3
 */
#ifndef PUBLIC_DEFINITIONS_H
#define PUBLIC_DEFINITIONS_H

#include "teamlog/logtypes.h"

#define TS3_MAX_SIZE_CHANNEL_NAME 40
#define TS3_MAX_SIZE_VIRTUALSERVER_NAME 64
#define TS3_MAX_SIZE_CLIENT_NICKNAME 64
#define TS3_MIN_SIZE_CLIENT_NICKNAME 3
#define TS3_MAX_SIZE_REASON_MESSAGE 80

#define TS3_MAX_SIZE_TEXTMESSAGE 8192
#define TS3_MAX_SIZE_CHANNEL_TOPIC 255
#define TS3_MAX_SIZE_CHANNEL_DESCRIPTION 8192
#define TS3_MAX_SIZE_VIRTUALSERVER_WELCOMEMESSAGE 1024
#define TS3_SIZE_MYTSID 44

#define TS3_MIN_SECONDS_CLIENTID_REUSE 300

#if defined(WIN32) || defined(__WIN32__) || defined(_WIN32)
    typedef unsigned __int16 anyID;
    typedef unsigned __int64 uint64;
    #ifdef BUILDING_DLL
        #define EXPORTDLL __declspec(dllexport)
    #else
        #define EXPORTDLL
    #endif
#else
    #include <stdint.h>
    typedef uint16_t anyID;
    typedef uint64_t uint64;
    #ifdef BUILDING_DLL
        #define EXPORTDLL __attribute__ ((visibility("default")))
    #else
        #define EXPORTDLL
    #endif
#endif

enum TalkStatus {
    STATUS_NOT_TALKING = 0,
    STATUS_TALKING = 1,
    STATUS_TALKING_WHILE_DISABLED = 2,
};

enum CodecType {
    CODEC_SPEEX_NARROWBAND = 0,
    CODEC_SPEEX_WIDEBAND,
    CODEC_SPEEX_ULTRAWIDEBAND,
    CODEC_CELT_MONO,
    CODEC_OPUS_VOICE,
    CODEC_OPUS_MUSIC,
};

enum CodecEncryptionMode {
    CODEC_ENCRYPTION_PER_CHANNEL = 0,
    CODEC_ENCRYPTION_FORCED_OFF,
    CODEC_ENCRYPTION_FORCED_ON,
};

enum TextMessageTargetMode {
    TextMessageTarget_CLIENT=1,
    TextMessageTarget_CHANNEL,
    TextMessageTarget_SERVER,
    TextMessageTarget_MAX
};

enum MuteInputStatus {
    MUTEINPUT_NONE = 0,
    MUTEINPUT_MUTED,
};

enum MuteOutputStatus {
    MUTEOUTPUT_NONE = 0,
    MUTEOUTPUT_MUTED,
};

enum HardwareInputStatus {
    HARDWAREINPUT_DISABLED = 0,
    HARDWAREINPUT_ENABLED,
};

enum HardwareOutputStatus {
    HARDWAREOUTPUT_DISABLED = 0,
    HARDWAREOUTPUT_ENABLED,
};

enum InputDeactivationStatus {
    INPUT_ACTIVE = 0,
    INPUT_DEACTIVATED = 1,
};

enum ReasonIdentifier {
    REASON_NONE                              = 0,
    REASON_MOVED                             = 1,
    REASON_SUBSCRIPTION                      = 2,
    REASON_LOST_CONNECTION                   = 3,
    REASON_KICK_CHANNEL                      = 4,
    REASON_KICK_SERVER                       = 5,
    REASON_KICK_SERVER_BAN                   = 6,
    REASON_SERVERSTOP                        = 7,
    REASON_CLIENTDISCONNECT                  = 8,
    REASON_CHANNELUPDATE                     = 9,
    REASON_CHANNELEDIT                       = 10,
    REASON_CLIENTDISCONNECT_SERVER_SHUTDOWN  = 11,
};

enum ChannelProperties {
    CHANNEL_NAME = 0,
    CHANNEL_TOPIC,
    CHANNEL_DESCRIPTION,
    CHANNEL_PASSWORD,
    CHANNEL_CODEC,
    CHANNEL_CODEC_QUALITY,
    CHANNEL_MAXCLIENTS,
    CHANNEL_MAXFAMILYCLIENTS,
    CHANNEL_ORDER,
    CHANNEL_FLAG_PERMANENT,
    CHANNEL_FLAG_SEMI_PERMANENT,
    CHANNEL_FLAG_DEFAULT,
    CHANNEL_FLAG_PASSWORD,
    CHANNEL_CODEC_LATENCY_FACTOR,
    CHANNEL_CODEC_IS_UNENCRYPTED,
    CHANNEL_SECURITY_SALT,
    CHANNEL_DELETE_DELAY,
    CHANNEL_UNIQUE_IDENTIFIER,
    CHANNEL_ENDMARKER,
};

enum ClientProperties {
    CLIENT_UNIQUE_IDENTIFIER = 0,
    CLIENT_NICKNAME,
    CLIENT_VERSION,
    CLIENT_PLATFORM,
    CLIENT_FLAG_TALKING,
    CLIENT_INPUT_MUTED,
    CLIENT_OUTPUT_MUTED,
    CLIENT_OUTPUTONLY_MUTED,
    CLIENT_INPUT_HARDWARE,
    CLIENT_OUTPUT_HARDWARE,
    CLIENT_INPUT_DEACTIVATED,
    CLIENT_IDLE_TIME,
    CLIENT_DEFAULT_CHANNEL,
    CLIENT_DEFAULT_CHANNEL_PASSWORD,
    CLIENT_SERVER_PASSWORD,
    CLIENT_META_DATA,
    CLIENT_IS_MUTED,
    CLIENT_IS_RECORDING,
    CLIENT_VOLUME_MODIFICATOR,
    CLIENT_VERSION_SIGN,
    CLIENT_SECURITY_HASH,
    CLIENT_ENCRYPTION_CIPHERS,
    CLIENT_ENDMARKER,
};

enum VirtualServerProperties {
    VIRTUALSERVER_UNIQUE_IDENTIFIER = 0,
    VIRTUALSERVER_NAME,
    VIRTUALSERVER_WELCOMEMESSAGE,
    VIRTUALSERVER_PLATFORM,
    VIRTUALSERVER_VERSION,
    VIRTUALSERVER_MAXCLIENTS,
    VIRTUALSERVER_PASSWORD,
    VIRTUALSERVER_CLIENTS_ONLINE,
    VIRTUALSERVER_CHANNELS_ONLINE,
    VIRTUALSERVER_CREATED,
    VIRTUALSERVER_UPTIME,
    VIRTUALSERVER_CODEC_ENCRYPTION_MODE,
    VIRTUALSERVER_ENCRYPTION_CIPHERS,
    VIRTUALSERVER_ENDMARKER,
};

enum ConnectionProperties {
    CONNECTION_PING = 0,
    CONNECTION_PING_DEVIATION,
    CONNECTION_CONNECTED_TIME,
    CONNECTION_IDLE_TIME,
    CONNECTION_CLIENT_IP,
    CONNECTION_CLIENT_PORT,
    CONNECTION_SERVER_IP,
    CONNECTION_SERVER_PORT,
    CONNECTION_PACKETS_SENT_SPEECH,
    CONNECTION_PACKETS_SENT_KEEPALIVE,
    CONNECTION_PACKETS_SENT_CONTROL,
    CONNECTION_PACKETS_SENT_TOTAL,
    CONNECTION_BYTES_SENT_SPEECH,
    CONNECTION_BYTES_SENT_KEEPALIVE,
    CONNECTION_BYTES_SENT_CONTROL,
    CONNECTION_BYTES_SENT_TOTAL,
    CONNECTION_PACKETS_RECEIVED_SPEECH,
    CONNECTION_PACKETS_RECEIVED_KEEPALIVE,
    CONNECTION_PACKETS_RECEIVED_CONTROL,
    CONNECTION_PACKETS_RECEIVED_TOTAL,
    CONNECTION_BYTES_RECEIVED_SPEECH,
    CONNECTION_BYTES_RECEIVED_KEEPALIVE,
    CONNECTION_BYTES_RECEIVED_CONTROL,
    CONNECTION_BYTES_RECEIVED_TOTAL,
    CONNECTION_PACKETLOSS_SPEECH,
    CONNECTION_PACKETLOSS_KEEPALIVE,
    CONNECTION_PACKETLOSS_CONTROL,
    CONNECTION_PACKETLOSS_TOTAL,
    CONNECTION_SERVER2CLIENT_PACKETLOSS_SPEECH,
    CONNECTION_SERVER2CLIENT_PACKETLOSS_KEEPALIVE,
    CONNECTION_SERVER2CLIENT_PACKETLOSS_CONTROL,
    CONNECTION_SERVER2CLIENT_PACKETLOSS_TOTAL,
    CONNECTION_CLIENT2SERVER_PACKETLOSS_SPEECH,
    CONNECTION_CLIENT2SERVER_PACKETLOSS_KEEPALIVE,
    CONNECTION_CLIENT2SERVER_PACKETLOSS_CONTROL,
    CONNECTION_CLIENT2SERVER_PACKETLOSS_TOTAL,
    CONNECTION_BANDWIDTH_SENT_LAST_SECOND_SPEECH,
    CONNECTION_BANDWIDTH_SENT_LAST_SECOND_KEEPALIVE,
    CONNECTION_BANDWIDTH_SENT_LAST_SECOND_CONTROL,
    CONNECTION_BANDWIDTH_SENT_LAST_SECOND_TOTAL,
    CONNECTION_BANDWIDTH_SENT_LAST_MINUTE_SPEECH,
    CONNECTION_BANDWIDTH_SENT_LAST_MINUTE_KEEPALIVE,
    CONNECTION_BANDWIDTH_SENT_LAST_MINUTE_CONTROL,
    CONNECTION_BANDWIDTH_SENT_LAST_MINUTE_TOTAL,
    CONNECTION_BANDWIDTH_RECEIVED_LAST_SECOND_SPEECH,
    CONNECTION_BANDWIDTH_RECEIVED_LAST_SECOND_KEEPALIVE,
    CONNECTION_BANDWIDTH_RECEIVED_LAST_SECOND_CONTROL,
    CONNECTION_BANDWIDTH_RECEIVED_LAST_SECOND_TOTAL,
    CONNECTION_BANDWIDTH_RECEIVED_LAST_MINUTE_SPEECH,
    CONNECTION_BANDWIDTH_RECEIVED_LAST_MINUTE_KEEPALIVE,
    CONNECTION_BANDWIDTH_RECEIVED_LAST_MINUTE_CONTROL,
    CONNECTION_BANDWIDTH_RECEIVED_LAST_MINUTE_TOTAL,
    CONNECTION_ENDMARKER,
};

typedef struct {
    float x;
    float y;
    float z;
} TS3_VECTOR;

enum GroupWhisperType {
    GROUPWHISPERTYPE_SERVERGROUP        = 0,
    GROUPWHISPERTYPE_CHANNELGROUP       = 1,
    GROUPWHISPERTYPE_CHANNELCOMMANDER   = 2,
    GROUPWHISPERTYPE_ALLCLIENTS         = 3,
    GROUPWHISPERTYPE_ENDMARKER,
};

enum GroupWhisperTargetMode {
    GROUPWHISPERTARGETMODE_ALL                   = 0,
    GROUPWHISPERTARGETMODE_CURRENTCHANNEL        = 1,
    GROUPWHISPERTARGETMODE_PARENTCHANNEL         = 2,
    GROUPWHISPERTARGETMODE_ALLPARENTCHANNELS     = 3,
    GROUPWHISPERTARGETMODE_CHANNELFAMILY         = 4,
    GROUPWHISPERTARGETMODE_ANCESTORCHANNELFAMILY = 5,
    GROUPWHISPERTARGETMODE_SUBCHANNELS           = 6,
    GROUPWHISPERTARGETMODE_ENDMARKER,
};

enum MonoSoundDestination{
    MONO_SOUND_DESTINATION_ALL                  =0,
    MONO_SOUND_DESTINATION_FRONT_CENTER         =1,
    MONO_SOUND_DESTINATION_FRONT_LEFT_AND_RIGHT =2
};

enum SecuritySaltOptions {
    SECURITY_SALT_CHECK_NICKNAME  = 1,
    SECURITY_SALT_CHECK_META_DATA = 2
};

enum ClientCommand{
    CLIENT_COMMAND_requestConnectionInfo        =  0,
    CLIENT_COMMAND_requestClientMove            =  1,
    CLIENT_COMMAND_requestXXMuteClients         =  2,
    CLIENT_COMMAND_requestClientKickFromXXX     =  3,
    CLIENT_COMMAND_flushChannelCreation         =  4,
    CLIENT_COMMAND_flushChannelUpdates          =  5,
    CLIENT_COMMAND_requestChannelMove           =  6,
    CLIENT_COMMAND_requestChannelDelete         =  7,
    CLIENT_COMMAND_requestChannelDescription    =  8,
    CLIENT_COMMAND_requestChannelXXSubscribeXXX =  9,
    CLIENT_COMMAND_requestServerConnectionInfo  = 10,
    CLIENT_COMMAND_requestSendXXXTextMsg        = 11,
    CLIENT_COMMAND_filetransfers                = 12,
    CLIENT_COMMAND_ENDMARKER
};

enum ACLType{
    ACL_NONE       = 0,
    ACL_WHITE_LIST = 1,
    ACL_BLACK_LIST = 2
};

enum FTAction{
    FT_INIT_SERVER  = 0,
    FT_INIT_CHANNEL = 1,
    FT_UPLOAD       = 2,
    FT_DOWNLOAD     = 3,
    FT_DELETE       = 4,
    FT_CREATEDIR    = 5,
    FT_RENAME       = 6,
    FT_FILELIST     = 7,
    FT_FILEINFO     = 8
};

enum FileTransferState {
    FILETRANSFER_INITIALISING = 0,
    FILETRANSFER_ACTIVE,
    FILETRANSFER_FINISHED,
};

enum {
    FileListType_Directory = 0,
    FileListType_File,
};

#define MAX_VARIABLES_EXPORT_COUNT 64
struct VariablesExportItem{
    unsigned char itemIsValid;
    unsigned char proposedIsSet;
    const char* current;
    const char* proposed;
};

struct VariablesExport{
    struct VariablesExportItem items[MAX_VARIABLES_EXPORT_COUNT];
};

struct ClientMiniExport{
    anyID ID;
    uint64 channel;
    const char* ident;
    const char* nickname;
};

struct TransformFilePathExport{
    uint64 channel;
    const char* filename;
    int action;
    int transformedFileNameMaxSize;
    int channelPathMaxSize;
};

struct TransformFilePathExportReturns{
    char* transformedFileName;
    char* channelPath;
    int logFileAction;
};

struct FileTransferCallbackExport{
    anyID clientID;
    anyID transferID;
    anyID remoteTransferID;
    unsigned int status;
    const char* statusMessage;
    uint64 remotefileSize;
    uint64 bytes;
    int isSender;
};

#define BANDWIDTH_LIMIT_UNLIMITED 0xFFFFFFFFFFFFFFFFll

#endif /*PUBLIC_DEFINITIONS_H*/
